<MiRaiz>:

    random_label: random_label

    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "Test"
            color: 0.1, 0.1, 0.94
            font_size: 64
        Label:
            id: random_label
            text: "-"
            font_size: 64
        Button:
            text: "Generar"
            color: 0.1, 0.9, 0.9
            font_size: 32
            size: 100, 50
            on_press: 
